/**
 * @fileoverview Matriz maestra de permisos RBAC de IQ Basket.
 * @description Fuente única de verdad para permisos funcionales.
 */

import { UserRole } from "./roles.js";

export const Permission = Object.freeze({
  NAVIGATE_MODULE: "NAVIGATE_MODULE",
  SELECT_TEAM: "SELECT_TEAM",
  SELECT_SEASON: "SELECT_SEASON",
  VIEW_DASHBOARD: "VIEW_DASHBOARD",
  SYNC_DATA: "SYNC_DATA",
  VIEW_DATA_AUDIT: "VIEW_DATA_AUDIT",
  REPAIR_DATA_AUDIT: "REPAIR_DATA_AUDIT",
  VIEW_TEAM: "VIEW_TEAM",
  VIEW_ROSTER: "VIEW_ROSTER",
  VIEW_PLAYER_PROFILE: "VIEW_PLAYER_PROFILE",
  VIEW_PLAYER_STATS: "VIEW_PLAYER_STATS",
  VIEW_PLAYER_COMPARISON: "VIEW_PLAYER_COMPARISON",
  VIEW_PRIVATE_NOTES: "VIEW_PRIVATE_NOTES",
  EDIT_TACTICAL_NOTES: "EDIT_TACTICAL_NOTES",
  EDIT_PHYSICAL_NOTES: "EDIT_PHYSICAL_NOTES",
  EDIT_PLAYER_MASTER: "EDIT_PLAYER_MASTER",
  VIEW_GAMES: "VIEW_GAMES",
  CREATE_GAME: "CREATE_GAME",
  EDIT_GAME: "EDIT_GAME",
  DELETE_GAME: "DELETE_GAME",
  RECORD_LIVE_GAME: "RECORD_LIVE_GAME",
  VIEW_BOXSCORE: "VIEW_BOXSCORE",
  VIEW_LINEUPS: "VIEW_LINEUPS",
  VIEW_ADVANCED_TEAM_STATS: "VIEW_ADVANCED_TEAM_STATS",
  VIEW_ADVANCED_PLAYER_STATS: "VIEW_ADVANCED_PLAYER_STATS",
  USE_COMPARATOR: "USE_COMPARATOR",
  GENERATE_REPORT: "GENERATE_REPORT",
  EXPORT_REPORT: "EXPORT_REPORT",
  MANAGE_REPORTS: "MANAGE_REPORTS",
  USE_AI: "USE_AI",
  VIEW_FAMILY_ADVISOR: "VIEW_FAMILY_ADVISOR",
  EDIT_OWN_PROFILE: "EDIT_OWN_PROFILE",
  CHANGE_OWN_PASSWORD: "CHANGE_OWN_PASSWORD",
  VIEW_ACTIVE_ROLE: "VIEW_ACTIVE_ROLE",
  SIMULATE_ROLE: "SIMULATE_ROLE",
  VIEW_CLUBS: "VIEW_CLUBS",
  MANAGE_CLUBS: "MANAGE_CLUBS",
  MANAGE_TEAMS: "MANAGE_TEAMS",
  REQUEST_TEAM_ACCESS: "REQUEST_TEAM_ACCESS",
  APPROVE_TEAM_ACCESS: "APPROVE_TEAM_ACCESS",
  MANAGE_ROSTER: "MANAGE_ROSTER",
  VIEW_SEASONS: "VIEW_SEASONS",
  MANAGE_SEASONS: "MANAGE_SEASONS",
  VIEW_USERS: "VIEW_USERS",
  INVITE_USERS: "INVITE_USERS",
  ASSIGN_STANDARD_ROLES: "ASSIGN_STANDARD_ROLES",
  ASSIGN_PRIVILEGED_ROLES: "ASSIGN_PRIVILEGED_ROLES",
  MANAGE_TRANSLATIONS: "MANAGE_TRANSLATIONS"
});

const COMMON_READ = [
  Permission.NAVIGATE_MODULE,
  Permission.SELECT_TEAM,
  Permission.SELECT_SEASON,
  Permission.VIEW_DASHBOARD,
  Permission.VIEW_TEAM,
  Permission.VIEW_ROSTER,
  Permission.VIEW_PLAYER_PROFILE,
  Permission.VIEW_PLAYER_STATS,
  Permission.VIEW_GAMES,
  Permission.VIEW_BOXSCORE,
  Permission.VIEW_LINEUPS,
  Permission.VIEW_ADVANCED_TEAM_STATS,
  Permission.VIEW_ADVANCED_PLAYER_STATS,
  Permission.GENERATE_REPORT,
  Permission.EDIT_OWN_PROFILE,
  Permission.CHANGE_OWN_PASSWORD,
  Permission.VIEW_ACTIVE_ROLE,
  Permission.VIEW_CLUBS,
  Permission.VIEW_SEASONS
];

export const ROLE_PERMISSIONS = Object.freeze({
  [UserRole.SUPERADMIN]: Object.values(Permission),

  [UserRole.ADMIN]: [
    ...COMMON_READ,
    Permission.SYNC_DATA,
    Permission.VIEW_DATA_AUDIT,
    Permission.REPAIR_DATA_AUDIT,
    Permission.VIEW_PLAYER_COMPARISON,
    Permission.VIEW_PRIVATE_NOTES,
    Permission.EDIT_TACTICAL_NOTES,
    Permission.EDIT_PHYSICAL_NOTES,
    Permission.EDIT_PLAYER_MASTER,
    Permission.CREATE_GAME,
    Permission.EDIT_GAME,
    Permission.DELETE_GAME,
    Permission.RECORD_LIVE_GAME,
    Permission.USE_COMPARATOR,
    Permission.EXPORT_REPORT,
    Permission.MANAGE_REPORTS,
    Permission.USE_AI,
    Permission.VIEW_FAMILY_ADVISOR,
    Permission.MANAGE_CLUBS,
    Permission.MANAGE_TEAMS,
    Permission.APPROVE_TEAM_ACCESS,
    Permission.MANAGE_ROSTER,
    Permission.MANAGE_SEASONS,
    Permission.VIEW_USERS,
    Permission.INVITE_USERS,
    Permission.ASSIGN_STANDARD_ROLES
  ],

  [UserRole.ENTRENADOR]: [
    ...COMMON_READ,
    Permission.SYNC_DATA,
    Permission.VIEW_DATA_AUDIT,
    Permission.VIEW_PLAYER_COMPARISON,
    Permission.VIEW_PRIVATE_NOTES,
    Permission.EDIT_TACTICAL_NOTES,
    Permission.EDIT_PLAYER_MASTER,
    Permission.CREATE_GAME,
    Permission.EDIT_GAME,
    Permission.RECORD_LIVE_GAME,
    Permission.USE_COMPARATOR,
    Permission.EXPORT_REPORT,
    Permission.MANAGE_REPORTS,
    Permission.USE_AI,
    Permission.VIEW_FAMILY_ADVISOR,
    Permission.REQUEST_TEAM_ACCESS,
    Permission.MANAGE_ROSTER,
    Permission.MANAGE_SEASONS
  ],

  [UserRole.ANALISTA]: [
    ...COMMON_READ,
    Permission.SYNC_DATA,
    Permission.VIEW_DATA_AUDIT,
    Permission.VIEW_PLAYER_COMPARISON,
    Permission.VIEW_PRIVATE_NOTES,
    Permission.CREATE_GAME,
    Permission.EDIT_GAME,
    Permission.RECORD_LIVE_GAME,
    Permission.USE_COMPARATOR,
    Permission.EXPORT_REPORT,
    Permission.MANAGE_REPORTS,
    Permission.USE_AI,
    Permission.VIEW_FAMILY_ADVISOR,
    Permission.REQUEST_TEAM_ACCESS
  ],

  [UserRole.PREPARADOR_FISICO]: [
    ...COMMON_READ,
    Permission.VIEW_PRIVATE_NOTES,
    Permission.EDIT_PHYSICAL_NOTES,
    Permission.USE_COMPARATOR,
    Permission.EXPORT_REPORT,
    Permission.MANAGE_REPORTS,
    Permission.USE_AI,
    Permission.VIEW_FAMILY_ADVISOR,
    Permission.REQUEST_TEAM_ACCESS
  ],

  [UserRole.JUGADOR]: [
    Permission.NAVIGATE_MODULE,
    Permission.SELECT_TEAM,
    Permission.SELECT_SEASON,
    Permission.VIEW_DASHBOARD,
    Permission.VIEW_TEAM,
    Permission.VIEW_ROSTER,
    Permission.VIEW_PLAYER_PROFILE,
    Permission.VIEW_PLAYER_STATS,
    Permission.VIEW_GAMES,
    Permission.VIEW_BOXSCORE,
    Permission.VIEW_LINEUPS,
    Permission.VIEW_ADVANCED_TEAM_STATS,
    Permission.VIEW_ADVANCED_PLAYER_STATS,
    Permission.GENERATE_REPORT,
    Permission.EXPORT_REPORT,
    Permission.VIEW_FAMILY_ADVISOR,
    Permission.EDIT_OWN_PROFILE,
    Permission.CHANGE_OWN_PASSWORD,
    Permission.VIEW_ACTIVE_ROLE,
    Permission.VIEW_CLUBS,
    Permission.VIEW_SEASONS,
    Permission.REQUEST_TEAM_ACCESS
  ],

  [UserRole.FAMILIA_TUTOR]: [
    Permission.NAVIGATE_MODULE,
    Permission.SELECT_TEAM,
    Permission.SELECT_SEASON,
    Permission.VIEW_DASHBOARD,
    Permission.VIEW_TEAM,
    Permission.VIEW_ROSTER,
    Permission.VIEW_PLAYER_PROFILE,
    Permission.VIEW_PLAYER_STATS,
    Permission.VIEW_GAMES,
    Permission.VIEW_BOXSCORE,
    Permission.VIEW_LINEUPS,
    Permission.VIEW_ADVANCED_TEAM_STATS,
    Permission.VIEW_ADVANCED_PLAYER_STATS,
    Permission.GENERATE_REPORT,
    Permission.EXPORT_REPORT,
    Permission.USE_AI,
    Permission.VIEW_FAMILY_ADVISOR,
    Permission.EDIT_OWN_PROFILE,
    Permission.CHANGE_OWN_PASSWORD,
    Permission.VIEW_ACTIVE_ROLE,
    Permission.VIEW_CLUBS,
    Permission.VIEW_SEASONS,
    Permission.REQUEST_TEAM_ACCESS
  ],

  [UserRole.VISOR]: [
    ...COMMON_READ,
    Permission.VIEW_PLAYER_COMPARISON,
    Permission.VIEW_DATA_AUDIT,
    Permission.USE_COMPARATOR,
    Permission.EXPORT_REPORT,
    Permission.USE_AI,
    Permission.EDIT_OWN_PROFILE,
    Permission.CHANGE_OWN_PASSWORD,
    Permission.REQUEST_TEAM_ACCESS
  ],

  [UserRole.INVITADO]: [
    ...COMMON_READ,
    Permission.VIEW_PLAYER_COMPARISON,
    Permission.USE_COMPARATOR,
    Permission.USE_AI,
    Permission.VIEW_FAMILY_ADVISOR,
    Permission.EDIT_OWN_PROFILE,
    Permission.CHANGE_OWN_PASSWORD,
    Permission.REQUEST_TEAM_ACCESS
  ]
});

export const AI_MONTHLY_LIMITS = Object.freeze({
  [UserRole.SUPERADMIN]: Infinity,
  [UserRole.ADMIN]: 200,
  [UserRole.ENTRENADOR]: 100,
  [UserRole.ANALISTA]: 100,
  [UserRole.PREPARADOR_FISICO]: 50,
  [UserRole.JUGADOR]: 0,
  [UserRole.FAMILIA_TUTOR]: 10,
  [UserRole.VISOR]: 20,
  [UserRole.INVITADO]: 10
});

export const ROUTE_PERMISSIONS = Object.freeze({
  dashboard: Permission.VIEW_DASHBOARD,
  team: Permission.VIEW_TEAM,
  equipo: Permission.VIEW_TEAM,
  players: Permission.VIEW_ROSTER,
  jugadores: Permission.VIEW_ROSTER,
  player: Permission.VIEW_PLAYER_PROFILE,
  jugador: Permission.VIEW_PLAYER_PROFILE,
  games: Permission.VIEW_GAMES,
  partidos: Permission.VIEW_GAMES,
  game: Permission.VIEW_GAMES,
  live: Permission.RECORD_LIVE_GAME,
  hud: Permission.RECORD_LIVE_GAME,
  "live-hud": Permission.RECORD_LIVE_GAME,
  "easy-entry": Permission.RECORD_LIVE_GAME,
  easy: Permission.RECORD_LIVE_GAME,
  "entrada-facil": Permission.RECORD_LIVE_GAME,
  "live-entry": Permission.RECORD_LIVE_GAME,
  boxscore: Permission.VIEW_BOXSCORE,
  registro: Permission.VIEW_BOXSCORE,
  lineups: Permission.VIEW_LINEUPS,
  quintetos: Permission.VIEW_LINEUPS,
  advanced: Permission.VIEW_ADVANCED_TEAM_STATS,
  heatmap: Permission.VIEW_ADVANCED_PLAYER_STATS,
  calor: Permission.VIEW_ADVANCED_PLAYER_STATS,
  shotchart: Permission.VIEW_ADVANCED_PLAYER_STATS,
  comparator: Permission.USE_COMPARATOR,
  comparador: Permission.USE_COMPARATOR,
  reports: Permission.GENERATE_REPORT,
  informes: Permission.GENERATE_REPORT,
  informe: Permission.GENERATE_REPORT,
  "family-advisor": Permission.VIEW_FAMILY_ADVISOR,
  family: Permission.VIEW_FAMILY_ADVISOR,
  familia: Permission.VIEW_FAMILY_ADVISOR,
  familias: Permission.VIEW_FAMILY_ADVISOR,
  bienestar: Permission.VIEW_FAMILY_ADVISOR,
  advisor: Permission.VIEW_FAMILY_ADVISOR,
  ask: Permission.USE_AI,
  "ask-ai": Permission.USE_AI,
  pregunta: Permission.USE_AI,
  preguntale: Permission.USE_AI,
  ai: Permission.USE_AI,
  ia: Permission.USE_AI,
  profile: Permission.EDIT_OWN_PROFILE,
  perfil: Permission.EDIT_OWN_PROFILE,
  settings: Permission.VIEW_ACTIVE_ROLE,
  configuracion: Permission.VIEW_ACTIVE_ROLE,
  translations: Permission.MANAGE_TRANSLATIONS
});

export default Permission;
